
package ruleBase;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "RequestBankRules", targetNamespace = "http://wsdl/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RequestBankRules {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBanks", targetNamespace = "http://wsdl/", className = "ruleBase.GetBanks")
    @ResponseWrapper(localName = "getBanksResponse", targetNamespace = "http://wsdl/", className = "ruleBase.GetBanksResponse")
    @Action(input = "http://wsdl/RequestBankRules/getBanksRequest", output = "http://wsdl/RequestBankRules/getBanksResponse")
    public List<String> getBanks(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

}
